Change command order
pos-lifestyle/pos-finance-docker pull request #6
Opened 2019-06-25 09:04 UTC by jhae-de

When ruuning `make build` I often faced a hash sum mismatch issue.

`Failed to fetch http://security-cdn.debian.org/debian-security/pool/updates/main/i/icu/libicu-dev_57.1-6+deb9u2_amd64.deb Hash Sum mismatch`

Changing some command order solved this problem for me.

2019-06-25 09:37 UTC, ChriRas submitted a review, later dismissed

2019-06-25 09:38 UTC, Aeroek submitted a review, later dismissed

2019-06-25 10:30 UTC, FrankGiesecke requested changes
```
    && apt-get clean \	
    && rm -rf /var/lib/apt/lists/*	
```

These commands ave to be the last in a runt statement which uses `apt-get`.  
The reason why:
With these commands, the apt cache will be removed from the resulting layer. If tis isn't done, the whole cache will be kept in the docker layer which results in a much bigger layer size.

2019-06-25 10:45 UTC, jhae-de commented
So what can be the solution? Running those commands twice (before and after install)?

2019-06-26 17:33 UTC, jhae-de commented
Won't fix, can't reproduce.

2019-06-26 17:33 UTC, closed without merging