Add mysql extension to cli container
pos-lifestyle/pos-finance-docker pull request #9
Opened 2019-07-22 15:22 UTC by ChriRas

This is required for the market importer.

2019-07-22 16:27 UTC, jhae-de requested changes

2019-07-22 16:27 UTC, jhae-de commented on php-cli/Dockerfile
> +        pdo_mysql \
Please keep alphabetical order.

2019-07-23 05:42 UTC, Aeroek submitted a review, later dismissed

2019-07-23 15:31 UTC, jhae-de approved these changes

2019-07-23 21:35 UTC, FrankGiesecke approved these changes

2019-07-24 07:06 UTC, Aeroek approved these changes

2019-07-25 09:41 UTC, merged